# Generated by Django 4.1.3 on 2022-11-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityNames',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255, null=True, unique=True)),
                ('city_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.TextField(max_length=255, unique=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.citynames')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(max_length=255, unique=True)),
                ('brand_name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('base_category', models.TextField(blank=True, null=True)),
                ('sub_category', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='price_weight_location_relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('location_map_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.location')),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
